### ISSUE TITLE
how to install ?

### ISSUE THREAD

**Issue by Anikmoujegy** [kamilburda/batcher#1]
Please add the process of installation in .README file.

**Comment by kamilburda** [comment]
It's not ready yet :) I'll make this clearer in the readme.

In the meantime, you can use the [Export Layers](https://github.com/kamilburda/gimp-export-layers) plug-in for GIMP 2.10, which has the same features.

Batcher will in its first release be a port of Export Layers for GIMP 2.99.

**Comment by kamilburda** [comment]
The first version is finally released. Installation instructions are on the [plug-in page](https://kamilburda.github.io/batcher/).
