### ISSUE TITLE
does this plugin work with the flatpak?

### ISSUE THREAD

**Issue by duvjones** [kamilburda/batcher#11]
Excuse me, but does this plugin work with the flatpak and python 3.11?
I have download the zip, extracted it in the plugin's folder ( /home/<me>/.var/app/org.gimpGIMP/config/GIMP/2.99/plugins ) and I can't seem to get it to work... I wonder if their is anything that I missed?

**Comment by kamilburda** [comment]
Are you running GIMP 2.99.18? The plug-in (as of version 0.2) will not work with earlier GIMP versions.

The installation path should be `/home/username/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins`. I.e. inside `plug-ins`, there should be a `batcher` folder, and inside `batcher` you should see `batcher.py` and a couple of other subfolders.

You can double-check if the `plug-ins` path is recognized by GIMP by going to `Edit -> Preferences -> Folders -> Plug-ins`. If not, add it or use another available path.

Coincidentally, I released a new version (0.3) just a while ago. I tested it using the GIMP flatpak installation on Ubuntu 23.10 and Python 3.11. The `File -> Export Layers...` menu entry should be displayed.

**Comment by duvjones** [comment]
> Are you running GIMP 2.99.18? The plug-in (as of version 0.2) will not work with earlier GIMP versions.

I am, on Fedora 40.

> The installation path should be `/home/username/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins`. I.e. inside `plug-ins`, there should be a `batcher` folder, and inside `batcher` you should see `batcher.py` and a couple of other subfolders.

That I have done



> Coincidentally, I released a new version (0.3) just a while ago, you can try that version instead. I tested it using the GIMP flatpak installation on Ubuntu 23.10 and Python 3.11. The `File -> Export Layers...` menu entry should be displayed.

Ok, got that and extracted it to the plug-ins folder.

> If it still doesn't work, check the contents of `/home/username/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/error.log`.

Ok, that is odd... there is no log flie. 


> 
> If there is no such file, then you could try running GIMP from the terminal:
> 
> ```
> flatpak run org.gimp.GIMP//beta
> ```
> 
> and paste the output here.


This is what I got... I don't think that there is anything useful here


```
gimp_font_factory_load_names: 99 unsupported fonts were ignored. Set the GIMP_DEBUG_FONTS environment variable for a listing.
set device 'Wayland Pointer' to mode: disabled
gimp_imagefile_icon_callback: Error when getting information for file “/home/username/Downloads/Images/png/遠坂凜.png”: No such file or directory
gimp_imagefile_icon_callback: Error when getting information for file “/home/username/.cache/.fr-SK6GN2/PSDs/Yuno.psd”: No such file or directory
gimp_imagefile_icon_callback: Error when getting information for file “/run/media/username/ME-2TB.Art/drive-download/drive-download-20220804T231817Z-001/IvyXmas.psd”: No such file or directory
gimp_imagefile_icon_callback: Error when getting information for file “/home/username/Downloads/Images/png/Stuff/stuff/%E3%83%8A%E3%83%AB%E3%83%A1%E3%82%A2%E3%81%95%E3%82%93/âiâïâüâAé│é±/âiâïâüâAé│é±.png”: No such file or directory
gimp_imagefile_icon_callback: Error when getting information for file “/home/username/Downloads/Images/png/Stuff/stuff/%E3%83%8A%E3%83%AB%E3%83%A1%E3%82%A2%E3%81%95%E3%82%93/âiâïâüâAé│é±/âiâïâüâAé│é±.jpg”: No such file or directory
gimp_imagefile_icon_callback: Error when getting information for file “/home/username/Downloads/Images/png/Stuff/stuff/%E3%83%8A%E3%83%AB%E3%83%A1%E3%82%A2%E3%81%95%E3%82%93/âiâïâüâAé│é±/âiâïâüâAé│é±.psd”: No such file or directory
set device 'Wayland Finger Scrolling' to mode: disabled

```

**Comment by kamilburda** [comment]
Thank you for the information. I'll test the plug-in on Fedora 40.

In the meantime, are you able to run other Python plug-ins, such as `Image -> Filters -> Decor -> Fog...`?

**Comment by duvjones** [comment]
> Thank you for the information. I'll test the plug-in on Fedora 40.
> 
> In the meantime:
> 
>     * Are you able to run other Python plug-ins, such as `Image -> Filters -> Decor -> Fog...`?

Sort of, When using `Filters -> Decor -> Fog...` it seems to work, but it does toss up an message.
"Plug-in 'Fog' left image undo in inconsistent state, closing open undo groups."

>     * Check if the `batcher/batcher.py` file is executable (has the executable bit set).
That is enabled...

**Comment by kamilburda** [comment]
Thanks for the info. The important thing is that the Fog plug-in is displayed and Python is working as intended.

On a fresh Fedora 40 install, I was able to get it running by installing it to `/home/username/.var/...` folder.

Since there are no error logs nor any hints in the console output that the plug-in crashes, it likely means that GIMP does not pick up on (register) the plug-in for some strange reason. This puzzles me, more so even that the file permissions on your end seem to be OK.

Try perhaps placing the `batcher` folder under one of the other `plug-ins` folders available (these should be `/app/lib/gimp/2.99/plug-ins` and `/app/extensions/plug-ins`, at least that's what is listed in GIMP).

**Comment by duvjones** [comment]
> Thanks for the info. The important thing is that the Fog plug-in is displayed and Python is working as intended.

> Try perhaps placing the `batcher` folder under one of the other `plug-ins` folders available (these should be `/app/lib/gimp/2.99/plug-ins` and `/app/extensions/plug-ins`, at least that's what I see being listed in GIMP).

Ok, it would seem to me that those two locations on the drive don't exist, every time I have attempted to look into them, nautilus seems to fail to do so.

**Comment by kamilburda** [comment]
> Ok, it would seem to me that those two locations on the drive don't exist, every time I have attempted to look into them, nautilus seems to fail to do so.

You are indeed right, looks like these directories are relative to some other path managed by the flatpak installation. The `/app/lib/gimp/2.99/plug-ins` path is mapped to `/home/username/.local/share/flatpak/app/org.gimp.GIMP/current/active/files/lib/gimp/2.99/plug-ins`, which is where you will find plug-ins bundled with GIMP.

**Comment by duvjones** [comment]
Okay, that worked... Thank you for the help.

**Comment by kamilburda** [comment]
Glad I could help. ☺️

**Comment by XenHat** [comment]
I had to create a new folder, add it to the plug-ins folder list, and put the plugin there, but I finally got it working as well.

**Comment by kamilburda** [comment]
That's a good idea. I'll update installation instructions before the next release to suggest this in case the plug-ins folders are relative and thus difficult to locate by hand.
